image: gcc4.8
script:
  - sudo apt-get install -y libmpdclient-dev &> /dev/null
  - cmake . -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_BUILD_TYPE=Debug
  - make VERBOSE=1 
notify:
  email:
    recipients:
      - andy@ndyk.de
  irc:
    server: irc.freenode.org
    nick: droneBot
    channel: '#nicotest'
    on_started: true
    on_success: true
    on_failure: true

